FROM python:3.12-slim

#  Ваш код здесь #
WORKDIR /app
COPY . .
ENV DB_HOST 172.20.0.10
RUN pip install -r requirements.txt
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 